# create a keycloak pod and services using postgres as database
kind: Template
apiVersion: v1
metadata: 
  name: keycloak
  annotations:
    description: Creates a Keycloak cluster with postgres
  labels:
    app: keycloak-app
  
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: postgres-service
    labels:
      app: keycloak-app
  spec:
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector: 
      component: postgres
    #portalIP: 
    #  type: ClusterIP
    sessionAffinity: None
 
- kind: Service
  apiVersion: v1
  metadata: 
    name: keycloak-http-service
    labels:
      app: keycloak-app
  spec: 
    ports: 
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector: 
      component: keycloak

- kind: Service
  apiVersion: v1
  metadata: 
    name: keycloak-https-service
    labels:
      app: keycloak-app
  spec: 
    ports: 
    - port: 443
      protocol: TCP
      targetPort: 8443
    selector: 
      component: keycloak

- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: postgres-controler
    labels:
      app: keycloak-app
    
  spec: 
    replicas: 1
    selector: 
      component: postgres
    template: 
      metadata: 
        labels: 
          component: postgres
      spec: 
        containers: 
        - image: postgres
          name: postgres-container
          ports: 
          - containerPort: 5432
          env: 
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_ROOT_PASSWORD
              value: password
      
- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: keycloak-controler
    labels:
      app: keycloak-app
  spec: 
    replicas: 1
    selector: 
      component: keycloak
    template: 
      metadata: 
        labels: 
          component: keycloak
      spec: 
        containers: 
        - image: clinte/keycloak-openshift
          name: keycloak-container
          ports: 
          - containerPort: 8080
            name: http
          - containerPort: 8443
            name: admin
          env:
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            
- kind: Route
  apiVersion: v1
  metadata:
    name: keycloak-http
    namespace: default
    labels:
      server: keycloak
      app: keycloak-app
  spec:
    host: keycloak.vagrant.f8
    path: "/auth" 
    to:
      kind: Service
      name: keycloak-http-service

#- kind: Route
#  apiVersion: v1
#  metadata:
#    name: keycloak-https
#    namespace: default
#    labels:
#      server: keycloak
#      app: keycloak-app
#  spec:
#    host: keycloak.vagrant.f8
#    path: "/auth" 
#    to:
#      kind: Service
#      name: keycloak-https-service
#    tls:
#      termination: passthrough      
#      
<<<<<<< HEAD
=======

>>>>>>> https route removed
#parameters: 
#  - name: TEST_PARAM
#    description: For test
#    value: set in template.yaml
           
