# create a keycloak pod and services using postgres as database
kind: Template
apiVersion: v1
metadata: 
  name: keycloak
  annotations:
    description: Creates a Keycloak cluster with postgres
  labels:
    app: keycloak-app
  
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: postgres-service
    labels:
      app: keycloak-app
  spec:
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector: 
      component: postgres
    #portalIP: 
    #  type: ClusterIP
    sessionAffinity: None
 
- kind: Service
  apiVersion: v1
  metadata: 
    name: keycloak-http-service
    labels:
      app: keycloak-app
  spec: 
    ports: 
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    selector: 
      component: keycloak

- kind: Service
  apiVersion: v1
  metadata: 
    name: keycloak-https-service
    labels:
      app: keycloak-app
  spec: 
    ports: 
    - port: 443
      protocol: TCP
      targetPort: 8443
    selector: 
      component: keycloak

- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: postgres-controler
    labels:
      app: keycloak-app
    
  spec: 
    replicas: 1
    selector: 
      component: postgres
    template: 
      metadata: 
        labels: 
          component: postgres
      spec: 
        containers: 
        - image: postgres
          name: postgres-container
          ports: 
          - containerPort: 5432
          env: 
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_ROOT_PASSWORD
              value: password
      
- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: keycloak-controler
    labels:
      app: keycloak-app
  spec: 
    replicas: 1
    selector: 
      component: keycloak
    template: 
      metadata: 
        labels: 
          component: keycloak
      spec: 
        containers: 
        - image: clinte/keycloak-openshift
          name: keycloak-container
          ports: 
          - containerPort: 8080
            name: http
          - containerPort: 8443
            name: https
          env:
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            
- kind: Route
  apiVersion: v1
  metadata:
    name: keycloak-http
    namespace: default
    labels:
      server: keycloak
      app: keycloak-app
  spec:
    host: keycloak.vagrant.f8
    path: "/auth" 
    to:
      kind: Service
      name: keycloak-http-service

- kind: Route
  apiVersion: v1
  metadata:
    name: keycloak-https
    namespace: default
    labels:
      server: keycloak-ssl
      app: keycloak-app
  spec:
    host: keycloak.vagrant.f8
#    path: "/auth" 
    to:
      kind: Service
      name: keycloak-https-service
    tls:
      termination: edge
      # server.pkcs8:
      key: |-
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCcvoqmveVfzlf2
        lMl3LQDPIH/WyY4kEmNe4S5lmS2TmnlI07cvuIBHw1JjjIN+Wp41xE5KEUbOiD5D
        0upCskT6T8oOXEYQA3WvHp+W8L9+o18Hr32viaUkRNM2nhoeow6GAbxSrQP1Ui+l
        kPfPH869YzN1dQgVy1XsoEODVfIhOabbp3oDSE5zM/8X/rbIBIum6H5zX/tpISAE
        peVDlXhBwu4WQxxj9PFutkcxILmv3syFqMMhPlSyOp2ayA9a8zoJPl+W14mEVeqo
        MKtyGD8SEm+fBFySnK+NZAKfJZZ5uMp+yr8ZDpMsNj9oQw/4sBalcp3HWHO4fzZS
        VcCc+UEzAgMBAAECggEAN9MQ9JPbVoTaBUM2gZBwolRT036TdjtqUsdmS98DQXeZ
        zJtCuec/IM/qzvOjfWPuxv10WKLQkgwqCOPcdQai1HeIYhbxCRECX+1LL2ns+cBb
        vxP8coFWZJVymBg0+0ZdjNKfbN6b80pjF9eKuqT8b60eDa4xw/lYT99ATE1W4Afk
        Cnvyuj0lGJk/bvA68ihK8gk5uog4gz3odmPdK2Vhl5ce66rJNXcOXfoz61+inq6g
        0TGjaeZkbyT3MI1f3HU7KO5NSQ3509elNgu3r88HMQ/4oBDRyXKL1RZrNuHu7tNc
        swt+hx1ar8xa+pKDK7L4UnuGKl/b95tzS2aJxGZAuQKBgQDzJziQDeUvz8076yqS
        Qn8vwILd3J6v4mkHkoQfs9dCCyXSGvQHAHhGIKTnlYdeEYWjRxqZApHB8kmrFRkC
        AKVwMMEjCmhKy+z57DTqAzH9O5Pl8zxJswx/hrK6aEQVg7hd3AcCx/torWyM0vsI
        CjhNZU+fDiEcB4Vrf7An1IdTdwKBgQClBpfl+aTj2oLOiSYHmys2mxQ81tRjt1iJ
        PFTG5Y9phWjiyWtkktUJ7IvzdW+XrMSsWD95hV40WARE3OpqnS9E6fHmHkKHzQvS
        rMWWpFZ63pvTRpOYI/Gn1OryldPlC4RtZipM6Oorol32jTFUlVSzKAf2k1VCT1Xp
        gGEI/AmXJQKBgF75DNDHfKNmKSWkPyaNrpv6N6NsztaoOpnoko7Hcear8APW30X0
        2wWZLo/+CbemZGpYFX16UXBNsJSQUwpDMltVz7peEEpWyKL9rdVRli7xHF2O2hd3
        RgRxmlHQ8/brUhHnJR3i+sHyKxn+Nmr3gvJIBgd8P1ZxYZ2RbD7CdnEVAoGAdEQh
        7sAk4PeJYzQTXBaBqpY1+ussdhitwvqDjCIeGS0KCYX5KMGeYMCMlXlupsDtS7Nc
        /SPujBha4Z13dqfJrtbYO9Wj8AORyds51nlwCF8gEAlQYUcpsaH76e+Pe3bS1TS+
        prMOkLFzXAp77+jJ5PNWMO36ip5UnA97zhWsOBUCgYAe0AAIEDFoXYKPhox3kgQQ
        e4rH6CkPU4cEqcBWmgQeAtGbt7yLsrgtmpVJeAMCFCF0C7dZG4L5TKPqoQsZmk3G
        s/fex1/xzy0F1VsRY+QoqS3tXxxmW3VkJutqxMah6rjkZrf3ZIGLjbb+vNkBRjon
        MLJ2GG9M3shaaYXVJl+w6w==
        -----END PRIVATE KEY-----
      # server.cer:
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIDuTCCAqGgAwIBAgIEVks5GjANBgkqhkiG9w0BAQsFADCBkDEnMCUGCSqGSIb3
        DQEJARYYY2xpbnQuZWFzdHdvb2xAZ21haWwuY29tMQswCQYDVQQGEwJERTEPMA0G
        A1UECAwGSGVzc2VuMQ4wDAYDVQQHDAVIYW5hdTEOMAwGA1UECgwFQ2xpbnQxFDAS
        BgNVBAsMC0RldmVsb3BtZW50MREwDwYDVQQDDAhjbGludC1jYTAeFw0xNTExMTcx
        NDI3MzBaFw0xNjExMTcxNDI3MzBaMIGOMScwJQYJKoZIhvcNAQkBFhhjbGludC5l
        YXN0d29vbEBnbWFpbC5jb20xCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZIZXNzZW4x
        DjAMBgNVBAcMBUhhbmF1MQ4wDAYDVQQKDAVDbGludDEUMBIGA1UECwwLRGV2ZWxv
        cG1lbnQxDzANBgNVBAMMBnNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
        AQoCggEBAJy+iqa95V/OV/aUyXctAM8gf9bJjiQSY17hLmWZLZOaeUjTty+4gEfD
        UmOMg35anjXETkoRRs6IPkPS6kKyRPpPyg5cRhADda8en5bwv36jXwevfa+JpSRE
        0zaeGh6jDoYBvFKtA/VSL6WQ988fzr1jM3V1CBXLVeygQ4NV8iE5ptunegNITnMz
        /xf+tsgEi6bofnNf+2khIASl5UOVeEHC7hZDHGP08W62RzEgua/ezIWowyE+VLI6
        nZrID1rzOgk+X5bXiYRV6qgwq3IYPxISb58EXJKcr41kAp8llnm4yn7KvxkOkyw2
        P2hDD/iwFqVyncdYc7h/NlJVwJz5QTMCAwEAAaMbMBkwFwYDVR0RAQH/BA0wC4IJ
        bG9jYWxob3N0MA0GCSqGSIb3DQEBCwUAA4IBAQCZLUSkHRBXaS+BdASCoPEUVdl7
        01UQaIATQSxTLsIie8Wqssr57Jv1VrrFInPjBNr7xQ77EJ8xJhKyDBY1tslA2oJH
        N5mYiqpdBe0uMTm9sdStljwmXa3AtmcvssZSPHtv/gZ2ePomOP6cgS52IDE2Bkal
        s82/IFzcNrJx9lelzSwA4LcFXZHarnH7/B7xjd+bmSZ5cRXW7PLcBkDbJPu0gt1M
        gaV+DcO62Hn2JmfrDsb19Wp5O+24Q0FGGZr5JfuqhL88kkRblOtYhIYCByLpgjXs
        9g7Y3CQtVJDGEpQbC27/DvuPFakRcZWI4OSZR1aYjAuIdSqWa4XZPj8oVaxI
        -----END CERTIFICATE-----
      # root_ca_cer:
      caCertificate: |-
        -----BEGIN CERTIFICATE-----
        MIIDvjCCAqagAwIBAgIEVks04jANBgkqhkiG9w0BAQsFADCBjzEnMCUGCSqGSIb3
        DQEJARYYY2xpbnQuZWFzdHdvb2xAZ21haWwuY29tMQswCQYDVQQGEwJERTEPMA0G
        A1UECAwGSGVzc2VuMQ4wDAYDVQQHDAVIYW5hdTEOMAwGA1UECgwFQ2xpbnQxFDAS
        BgNVBAsMC0RldmVsb3BtZW50MRAwDgYDVQQDDAdyb290LWNhMB4XDTE1MTExNzE0
        MDkxMloXDTE2MTExNzE0MDkxMlowgY8xJzAlBgkqhkiG9w0BCQEWGGNsaW50LmVh
        c3R3b29sQGdtYWlsLmNvbTELMAkGA1UEBhMCREUxDzANBgNVBAgMBkhlc3NlbjEO
        MAwGA1UEBwwFSGFuYXUxDjAMBgNVBAoMBUNsaW50MRQwEgYDVQQLDAtEZXZlbG9w
        bWVudDEQMA4GA1UEAwwHcm9vdC1jYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
        AQoCggEBAKpVONt9YzfnfCwDGsBbV5SLHPTcDdJb+7EsDeIsT7/XLe/1a2qEEOqD
        ktoDnK3liKmpwCu7X9dlcILtnTw7bYmR3DRN5jUq53JKLZs6isHnA2+FLR2yYfde
        dFG9yfV4L46L2PESkLyuMs5UKNWO9MCvSA9Qcl0YoW93kAChxrEtI10RX2RlVai8
        YR+pSwvADhOYhC8Yc9qwdbdgaJlo5x7j80mQdsmbEEOGGVKKmv2kFt8+8PYlj3WE
        CtkwXCYR/j33kkvoN9PlM3mI59RESsGwzmLSfpZtc5H0iBMgRSIfgTy/knNfUAq9
        vkMcUF69sAWkkUwkxBFXClh83EJhTA8CAwEAAaMgMB4wDwYDVR0TAQH/BAUwAwEB
        /zALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAFUy4l4V23riy0/ewpH7
        K89i1s0y3g3eHCgBot0VOygmN/vlSskT4+zA/+q47IjPbunfoThm78uI8bKWUoXe
        chEP134pWdkX9VdusfXk9KmybutPnmrokpj/G+wZjVBqVvdW2BwXOCAOVsij1t24
        LbRF/xAFREHwbsP4aOSECRtCd1CNRIww+Hpzof6SWXJg1L0Ly0EoLPBaSsqEAWjP
        R3uzBkSrqrdAvt7MuEqj5MnUr/tNpD4yseBvzdwPi0snZaFLtQlZTaanC53tjKj4
        sl8OFsL5meIc8r4Zn3Bj+iCmc3KYnt4aZx4ZjlmK6JvxcLt00dlfJM+Wts1ROn5e
        Awo=
        -----END CERTIFICATE-----
      
      
      #key:           -----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpnpiIZ6V0HmyzOtCY8h7WQkm+VcqGUngZQCxP3AgE0dVa86KDQ5eifXIr3pLUSknOl2stvK0+73smOTKAsW7VJuqGFw6IPEiF2lou+62eeR0vSfAn+9GEvWsmNezQZ5pXLZ70mcScD2xr+2v8URDU7fRUAnqVbe1x4YPUDnFT1UPC3J2+IwHeXspyTXZ0CGop1xxNF36wj7PxOhdy7WRqc0qfzfVGSGLOwmRil0o+F+oLPA5tlumH0gtFmA8NetiJ9dT0K4k2cGkr0ppTfEfoMF4p6fIu0Tuej++a6oBb9ca8IJgW8dpP0oZuyHMALjJwfWV+nKgGT87pj7bXminTAgMBAAECggEATYp7IKCBOrxN5QGWKtVE054qKCEAHLfGv4RevYNRByMF7jZCrM9Rmq7Oas+tP+9WHmOKU7ZVXNgN7ENpmvuCN187B2Gy+wTUApz3bVMQ48lqVhvu9dhgx9XwDd/JCtzR6dipOhixkMZcQmEF1KsajrzZXS5k67r9OXpm0aJonHG44j0tN+RUIaW1JAnQ4NbMO/ib2QQLvtTJMWqTZ7SpJl0j4rXOseKngoaCbX8rbWbAqCfc5q2OB63srTpeNHCH2BVQNswG+281oQsF3J0ybjFdLVEYkplfYTVcFYmqCdKDco5awpL/Y4ZuH9xqG2rscYlF6S16FvBdtjN6EmOYQQKBgQD3KPDiMp2iRKR2H1OlVs/Mz/T/XrquN4/ciX0Owxl1B2KV+0qFpp7QgxfJsEZqXiy7vbYGL3kHqUF+0ZvwZUe1g1ooFaP7mgXE9ylrLex8/tbCy1PCnCZDetBJWJeFh8/qjjpqDgRXerh0FS/52sqb752UkeUte6UtFJWyd0YPnQKBgQCvr6zZGcKn8LtL+DShg7E5C+n5yAPFlEUE8md6JCwb/7AHSdtDiRfAmRB7w7vHOhBiVRtZzlSqP/DT3CuZXpbVkjgTTXAgGzxapooXOX78GaWGDZjwLHTQINZMjIL4eYjvEjLmdNDItOyIAiTuhJGGibZCYLDjbuRsUeyvW368LwKBgQDtLGtjFGEx+p66/zq8OX70skYO3C9VyNmTLphEFzIRnEGdXOPZNtfFjVbBYxdfMPnKOrU2YE3K7T99W9VBLV9PrjlQp9uRL+8DYI5tXEdIdx9NE+JPqJoLPQosqAfWyknZchxZ8xN1gr0IH+DG6Y5tbtWPYSVDrRgHF27DMDOZ/QKBgDc7GDDMK2jWgls4tXsNRpqzhyPyYFUt7qDGgAdi9cb7k+BGtLq/j4sJ06fE+fSA6YOwU7/g4LcBEPnZno9BsFOF+0D+OECvr0KkVodEmQoyGdpRzgG7SCHiINzB066/rm/SHdRbZwOh9TYwzmF5pbJQ+s5VTWbChucSvkDGl8obAoGASA0fMpdarCwS4f6fzTeL5mgdheRCaZ+KtiFUZzfsqK985sC9BulmVmoy9TXIm4B3SgYXKTYx8UWeZmZTWjxwlwlnL9fr0DJ8BX87nMVG7fh6UHxQEfLs6714LhW5KZBDtZg9B7QEQGPQoPg48SYFYpR+ZTT91SJgy3cTJ5fxc34=-----END PRIVATE KEY-----
      #certificate:   -----BEGIN CERTIFICATE-----MIID1TCCAr2gAwIBAgIEVlMPLTANBgkqhkiG9w0BAQsFADCBkDEnMCUGCSqGSIb3DQEJARYYY2xpbnQuZWFzdHdvb2xAZ21haWwuY29tMQswCQYDVQQGEwJERTEPMA0GA1UECAwGSGVzc2VuMQ4wDAYDVQQHDAVIYW5hdTEOMAwGA1UECgwFQ2xpbnQxFDASBgNVBAsMC0RldmVsb3BtZW50MREwDwYDVQQDDAhjbGludC1jYTAeFw0xNTExMjMxMzA2MzVaFw0xNjExMjMxMzA2MzVaMIGQMScwJQYJKoZIhvcNAQkBFhhjbGludC5lYXN0d29vbEBnbWFpbC5jb20xCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZIZXNzZW4xDjAMBgNVBAcMBUhhbmF1MQ4wDAYDVQQKDAVDbGludDEUMBIGA1UECwwLRGV2ZWxvcG1lbnQxETAPBgNVBAMMCGtleWNsb2FrMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZ6YiGeldB5sszrQmPIe1kJJvlXKhlJ4GUAsT9wIBNHVWvOig0OXon1yK96S1EpJzpdrLbytPu97JjkygLFu1SbqhhcOiDxIhdpaLvutnnkdL0nwJ/vRhL1rJjXs0GeaVy2e9JnEnA9sa/tr/FEQ1O30VAJ6lW3tceGD1A5xU9VDwtydviMB3l7Kck12dAhqKdccTRd+sI+z8ToXcu1kanNKn831RkhizsJkYpdKPhfqCzwObZbph9ILRZgPDXrYifXU9CuJNnBpK9KaU3xH6DBeKenyLtE7no/vmuqAW/XGvCCYFvHaT9KGbshzAC4ycH1lfpyoBk/O6Y+215op0wIDAQABozUwMzAxBgNVHREBAf8EJzAlggp2YWdyYW50LmY4ggwqLnZhZ3JhbnQuZjiCCWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAkDW4gUt44INUBuO4Tj0URUvL0iEfcacCQ8NEfhtS2GIeMwZgzfsfZNaflLNcgeS9Y+fJki1Cc7pGAZnYzJqi+zzL6dHsFdOsGBmYc9jAyf7eTpJUDIWGDPnLFsy4aHmctkX9scTmc7AwL5zmW2pRMZNuyCwvCNyonbPymjcFrXJfEbVsem4GAQB+NX87WZqnw9cm5bUEovrbTYiG1V1m2j656Bz5i6AZBjGGV04rzx52oucsSK/6qfK2qXbTVo6CL0UM8g3rXTT3i6/xfCMg5VGJ6oNipLcnMfowCbUb+TesoU/9+uFR/RDYTUv21fc3HZ8SIYW0ZK2j+GKpJRny1w==-----END CERTIFICATE-----
      #caCertificate: -----BEGIN CERTIFICATE-----MIIDvjCCAqagAwIBAgIEVks04jANBgkqhkiG9w0BAQsFADCBjzEnMCUGCSqGSIb3DQEJARYYY2xpbnQuZWFzdHdvb2xAZ21haWwuY29tMQswCQYDVQQGEwJERTEPMA0GA1UECAwGSGVzc2VuMQ4wDAYDVQQHDAVIYW5hdTEOMAwGA1UECgwFQ2xpbnQxFDASBgNVBAsMC0RldmVsb3BtZW50MRAwDgYDVQQDDAdyb290LWNhMB4XDTE1MTExNzE0MDkxMloXDTE2MTExNzE0MDkxMlowgY8xJzAlBgkqhkiG9w0BCQEWGGNsaW50LmVhc3R3b29sQGdtYWlsLmNvbTELMAkGA1UEBhMCREUxDzANBgNVBAgMBkhlc3NlbjEOMAwGA1UEBwwFSGFuYXUxDjAMBgNVBAoMBUNsaW50MRQwEgYDVQQLDAtEZXZlbG9wbWVudDEQMA4GA1UEAwwHcm9vdC1jYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKpVONt9YzfnfCwDGsBbV5SLHPTcDdJb+7EsDeIsT7/XLe/1a2qEEOqDktoDnK3liKmpwCu7X9dlcILtnTw7bYmR3DRN5jUq53JKLZs6isHnA2+FLR2yYfdedFG9yfV4L46L2PESkLyuMs5UKNWO9MCvSA9Qcl0YoW93kAChxrEtI10RX2RlVai8YR+pSwvADhOYhC8Yc9qwdbdgaJlo5x7j80mQdsmbEEOGGVKKmv2kFt8+8PYlj3WECtkwXCYR/j33kkvoN9PlM3mI59RESsGwzmLSfpZtc5H0iBMgRSIfgTy/knNfUAq9vkMcUF69sAWkkUwkxBFXClh83EJhTA8CAwEAAaMgMB4wDwYDVR0TAQH/BAUwAwEB/zALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAFUy4l4V23riy0/ewpH7K89i1s0y3g3eHCgBot0VOygmN/vlSskT4+zA/+q47IjPbunfoThm78uI8bKWUoXechEP134pWdkX9VdusfXk9KmybutPnmrokpj/G+wZjVBqVvdW2BwXOCAOVsij1t24LbRF/xAFREHwbsP4aOSECRtCd1CNRIww+Hpzof6SWXJg1L0Ly0EoLPBaSsqEAWjPR3uzBkSrqrdAvt7MuEqj5MnUr/tNpD4yseBvzdwPi0snZaFLtQlZTaanC53tjKj4sl8OFsL5meIc8r4Zn3Bj+iCmc3KYnt4aZx4ZjlmK6JvxcLt00dlfJM+Wts1ROn5eAwo=-----END CERTIFICATE-----
      
#parameters: 
#  - name: TEST_PARAM
#    description: For test
#    value: set in template.yaml
           
