# create a keycloak pod and services using postgres as database
kind: Template
apiVersion: v1
metadata: 
  name: keycloak
  annotations:
    description: Creates a Keycloak cluster with postgres
  labels:
    app: keycloak-app
  
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: postgres-service
    labels:
      app: keycloak-app
  spec:
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector: 
      component: postgres
    #portalIP: 
    #  type: ClusterIP
    sessionAffinity: None
 
- kind: Service
  apiVersion: v1
  metadata: 
    name: keycloak-http-service
    labels:
      app: keycloak-app
  spec: 
    ports: 
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    selector: 
      component: keycloak

- kind: Service
  apiVersion: v1
  metadata: 
    name: keycloak-https-service
    labels:
      app: keycloak-app
  spec: 
    ports: 
    - port: 443
      protocol: TCP
      targetPort: 8443
    selector: 
      component: keycloak

- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: postgres-controler
    labels:
      app: keycloak-app
    
  spec: 
    replicas: 1
    selector: 
      component: postgres
    template: 
      metadata: 
        labels: 
          component: postgres
      spec: 
        containers: 
        - image: postgres
          name: postgres-container
          ports: 
          - containerPort: 5432
          env: 
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_ROOT_PASSWORD
              value: password
      
- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: keycloak-controler
    labels:
      app: keycloak-app
  spec: 
    replicas: 1
    selector: 
      component: keycloak
    template: 
      metadata: 
        labels: 
          component: keycloak
      spec: 
        containers:
        #- image: jboss/keycloak-ha-postgres
        - image: clinte/keycloak-openshift
        # - image: jboss/keycloak-postgres
          name: keycloak-container
          ports: 
          - containerPort: 8080
            name: http
          - containerPort: 8443
            name: https
          - containerPort: 9990
            name: admin
          - containerPort: 9993
            name: admins
          env:
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            
- kind: Route
  apiVersion: v1
  metadata:
    name: keycloak-https
    namespace: default
    labels:
      server: keycloak-https
      app: keycloak-app
  spec:
    host: keycloak.vagrant.f8
    to:
      kind: Service
      name: keycloak-http-service
#    tls:
#      termination: edge
#      # insecureEdgeTerminationPolicy: Allow
#      insecureEdgeTerminationPolicy: Redirect 
#      # keycloak.key:
#      key: |
#        -----BEGIN RSA PRIVATE KEY-----
#        MIIEowIBAAKCAQEAqZ6YiGeldB5sszrQmPIe1kJJvlXKhlJ4GUAsT9wIBNHVWvOi
#        g0OXon1yK96S1EpJzpdrLbytPu97JjkygLFu1SbqhhcOiDxIhdpaLvutnnkdL0nw
#        J/vRhL1rJjXs0GeaVy2e9JnEnA9sa/tr/FEQ1O30VAJ6lW3tceGD1A5xU9VDwtyd
#        viMB3l7Kck12dAhqKdccTRd+sI+z8ToXcu1kanNKn831RkhizsJkYpdKPhfqCzwO
#        bZbph9ILRZgPDXrYifXU9CuJNnBpK9KaU3xH6DBeKenyLtE7no/vmuqAW/XGvCCY
#        FvHaT9KGbshzAC4ycH1lfpyoBk/O6Y+215op0wIDAQABAoIBAE2KeyCggTq8TeUB
#        lirVRNOeKighABy3xr+EXr2DUQcjBe42QqzPUZquzmrPrT/vVh5jilO2VVzYDexD
#        aZr7gjdfOwdhsvsE1AKc921TEOPJalYb7vXYYMfV8A3fyQrc0enYqToYsZDGXEJh
#        BdSrGo682V0uZOu6/Tl6ZtGiaJxxuOI9LTfkVCGltSQJ0ODWzDv4m9kEC77UyTFq
#        k2e0qSZdI+K1zrHip4KGgm1/K21mwKgn3Oatjget7K06XjRwh9gVUDbMBvtvNaEL
#        BdydMm4xXS1RGJKZX2E1XBWJqgnSg3KOWsKS/2OGbh/cahtq7HGJRektehbwXbYz
#        ehJjmEECgYEA9yjw4jKdokSkdh9TpVbPzM/0/166rjeP3Il9DsMZdQdilftKhaae
#        0IMXybBGal4su722Bi95B6lBftGb8GVHtYNaKBWj+5oFxPcpay3sfP7WwstTwpwm
#        Q3rQSViXhYfP6o46ag4EV3q4dBUv+drKm++dlJHlLXulLRSVsndGD50CgYEAr6+s
#        2RnCp/C7S/g0oYOxOQvp+cgDxZRFBPJneiQsG/+wB0nbQ4kXwJkQe8O7xzoQYlUb
#        Wc5Uqj/w09wrmV6W1ZI4E01wIBs8WqaKFzl+/Bmlhg2Y8Cx00CDWTIyC+HmI7xIy
#        5nTQyLTsiAIk7oSRhom2QmCw427kbFHsr1t+vC8CgYEA7SxrYxRhMfqeuv86vDl+
#        9LJGDtwvVcjZky6YRBcyEZxBnVzj2TbXxY1WwWMXXzD5yjq1NmBNyu0/fVvVQS1f
#        T645UKfbkS/vA2CObVxHSHcfTRPiT6iaCz0KLKgH1spJ2XIcWfMTdYK9CB/gxumO
#        bW7Vj2ElQ60YBxduwzAzmf0CgYA3OxgwzCto1oJbOLV7DUaas4cj8mBVLe6gxoAH
#        YvXG+5PgRrS6v4+LCdOnxPn0gOmDsFO/4OC3ARD52Z6PQbBThftA/jhAr69CpFaH
#        RJkKMhnaUc4Bu0gh4iDcwdOuv65v0h3UW2cDofU2MM5heaWyUPrOVU1mwobnEr5A
#        xpfKGwKBgEgNHzKXWqwsEuH+n803i+ZoHYXkQmmfirYhVGc37KivfObAvQbpZlZq
#        MvU1yJuAd0oGFyk2MfFFnmZmU1o8cJcJZy/X69AyfAV/O5zFRu34elB8UBHy7Ou9
#        eC4VuSmQQ7WYPQe0BEBj0KD4OPEmBWKUfmU0/dUiYMt3EyeX8XN+
#        -----END RSA PRIVATE KEY-----
#
#      # keycloak_clint_ca_.cer:
#      certificate: |
#        -----BEGIN CERTIFICATE-----
#        MIID1TCCAr2gAwIBAgIEVlMPLTANBgkqhkiG9w0BAQsFADCBkDEnMCUGCSqGSIb3
#        DQEJARYYY2xpbnQuZWFzdHdvb2xAZ21haWwuY29tMQswCQYDVQQGEwJERTEPMA0G
#        A1UECAwGSGVzc2VuMQ4wDAYDVQQHDAVIYW5hdTEOMAwGA1UECgwFQ2xpbnQxFDAS
#        BgNVBAsMC0RldmVsb3BtZW50MREwDwYDVQQDDAhjbGludC1jYTAeFw0xNTExMjMx
#        MzA2MzVaFw0xNjExMjMxMzA2MzVaMIGQMScwJQYJKoZIhvcNAQkBFhhjbGludC5l
#        YXN0d29vbEBnbWFpbC5jb20xCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZIZXNzZW4x
#        DjAMBgNVBAcMBUhhbmF1MQ4wDAYDVQQKDAVDbGludDEUMBIGA1UECwwLRGV2ZWxv
#        cG1lbnQxETAPBgNVBAMMCGtleWNsb2FrMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
#        MIIBCgKCAQEAqZ6YiGeldB5sszrQmPIe1kJJvlXKhlJ4GUAsT9wIBNHVWvOig0OX
#        on1yK96S1EpJzpdrLbytPu97JjkygLFu1SbqhhcOiDxIhdpaLvutnnkdL0nwJ/vR
#        hL1rJjXs0GeaVy2e9JnEnA9sa/tr/FEQ1O30VAJ6lW3tceGD1A5xU9VDwtydviMB
#        3l7Kck12dAhqKdccTRd+sI+z8ToXcu1kanNKn831RkhizsJkYpdKPhfqCzwObZbp
#        h9ILRZgPDXrYifXU9CuJNnBpK9KaU3xH6DBeKenyLtE7no/vmuqAW/XGvCCYFvHa
#        T9KGbshzAC4ycH1lfpyoBk/O6Y+215op0wIDAQABozUwMzAxBgNVHREBAf8EJzAl
#        ggp2YWdyYW50LmY4ggwqLnZhZ3JhbnQuZjiCCWxvY2FsaG9zdDANBgkqhkiG9w0B
#        AQsFAAOCAQEAkDW4gUt44INUBuO4Tj0URUvL0iEfcacCQ8NEfhtS2GIeMwZgzfsf
#        ZNaflLNcgeS9Y+fJki1Cc7pGAZnYzJqi+zzL6dHsFdOsGBmYc9jAyf7eTpJUDIWG
#        DPnLFsy4aHmctkX9scTmc7AwL5zmW2pRMZNuyCwvCNyonbPymjcFrXJfEbVsem4G
#        AQB+NX87WZqnw9cm5bUEovrbTYiG1V1m2j656Bz5i6AZBjGGV04rzx52oucsSK/6
#        qfK2qXbTVo6CL0UM8g3rXTT3i6/xfCMg5VGJ6oNipLcnMfowCbUb+TesoU/9+uFR
#        /RDYTUv21fc3HZ8SIYW0ZK2j+GKpJRny1w==
#        -----END CERTIFICATE-----
#      
#      
#      # clint_ca_cer:
#      caCertificate: |
#        -----BEGIN CERTIFICATE-----
#        MIIDvzCCAqegAwIBAgIEVks2xjANBgkqhkiG9w0BAQsFADCBjzEnMCUGCSqGSIb3
#        DQEJARYYY2xpbnQuZWFzdHdvb2xAZ21haWwuY29tMQswCQYDVQQGEwJERTEPMA0G
#        A1UECAwGSGVzc2VuMQ4wDAYDVQQHDAVIYW5hdTEOMAwGA1UECgwFQ2xpbnQxFDAS
#        BgNVBAsMC0RldmVsb3BtZW50MRAwDgYDVQQDDAdyb290LWNhMB4XDTE1MTExNzE0
#        MTcxMFoXDTE2MTExNzE0MTcxMFowgZAxJzAlBgkqhkiG9w0BCQEWGGNsaW50LmVh
#        c3R3b29sQGdtYWlsLmNvbTELMAkGA1UEBhMCREUxDzANBgNVBAgMBkhlc3NlbjEO
#        MAwGA1UEBwwFSGFuYXUxDjAMBgNVBAoMBUNsaW50MRQwEgYDVQQLDAtEZXZlbG9w
#        bWVudDERMA8GA1UEAwwIY2xpbnQtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
#        ggEKAoIBAQCsKCfkyCAO1MXW8RLykvTVVcbpfPHcZzSD8driswmKYoGSK5N95PUx
#        X4netSk+A84Ymz0jy6hWRsBq4GHCNEk9qQPgaSaFClhCQ/f9k+Y9REENsq37XIOA
#        otkTIrBpYK5aIcCMzfzIQPLN0CglrxZtTOhV0U34/T7gOajWqPd196ug1msDIZu1
#        sQsF6tjyvYW6vuzHIlw2FOijdx3qfn3qSi4dXYIXvgXsd/HxM0MCydx4TDvYe03e
#        5j0rR3FkZ+iAYRIfS6enHJjAOnZkL2cERYlNslilmlUGMEeKU17Li6b36uf6zy9D
#        hgIEeqgXkPhzGFshh3pN+XjuviqpgPn5AgMBAAGjIDAeMA8GA1UdEwEB/wQFMAMB
#        Af8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQAVHYXjmkxZqCenAmY0
#        8J2DXz1xXKopt5Tz0UjmZgAXZ2CpoX7nBQu+ZBWaAXaJyGWVFh18Me+eWMpjk31r
#        L2yFDezszGAkrFxtV5knF8OQpH9gDY1fvXR7KVFmz2ZgbsE6Jtb8VacX5JewfVeb
#        k/gADunHVo+0eygvf4fS4ycwc7B3E0gqadnD0DgZZHi5MVuoSHNAv6RNMG4cLoib
#        cU7YRTXUyDvzZkjGFHyMg5csjiqDwqLiZ0ckPZtHOobrV9UrMG2LyCg3nxDoIv9E
#        Fd4peAswpJ9fEg+d9wphafAJcpkGJub6P+UG/XFARQYkoF32CBFhNVHnJK0nr2xw
#        d6Xk
#        -----END CERTIFICATE-----
                 
